#!/bin/bash
#
# Autor: Henryk Iwaniuk
#
# lxc-dump <container-name> <path>

echoerr() { echo "error: $@" 1>&2; }

print_help () {
cat << EOF
Usage: ${0##*/} <contaienr> [path]
dump script for lxd containers with lvm storage

Example:
    ${0##*/} guest99 /tmp
EOF
}

container_exists () {
	c_exists=$(lxc list $1 | awk -v cont=$1 '($2==cont) {print $2}')
	if [ -z "$c_exists" ]; then
		echoerr 'container does not exist';
		exit 22;
	fi
	return 1;
}

container_is_running () {
	c_running=$(lxc list --format csv -c n,s | grep RUNNING | grep $1)
	if [ -z "$c_running" ]; then
		return 0;
	fi
	return 1;
}

stop_container_if_running () {
    container_is_running $1;
    if [ $? -eq 1 ];
    then
        was_running=1;
        echo "stopping container $1";
        lxc stop $1
    fi
}

start_container_if_was_running () {
    if [ $was_running -eq 1 ]; then
        echo "starting container $1";
        lxc start $1;
    fi
}

if [ -z "$1" ];
then
    print_help;
    exit 0;
fi

was_running=0;
sDatum=`date +%Y_%m_%d-%H_%M_%S`;
hostname=$(hostname);
storage_pool_name="default";
path_to_private="/var/lib/lxd/storage-pools/$storage_pool_name/containers";
path_to_vg="/dev/lxc-$hostname"
default_path="."

container_name=$1;
container_exists $container_name;


if [ -z "$2" ];
then
    path=$(realpath "$default_path");
else
    path=$(realpath "$2");
fi

if [ ! -d "$path" ];
then
    echoerr "path $path does not exist.";
    exit 11;
fi

if [ -z "$2" ];
then
    filename=lxc-dump-$container_name-$sDatum.tar.gz;
else
    filename="$3";
fi

echo "Creating dump for container $container_name in $path";

stop_container_if_running $container_name;

mount -o ro $path_to_vg/containers_$container_name $path_to_private/$container_name;
cd $path_to_private/$container_name;
echo "Compressing container. This might take a while...";
tar cf -  --preserve-permissions --numeric-owner . | pigz -c  > $path/$filename
cd
umount $path_to_private/$container_name;

start_container_if_was_running $container_name;

echo "Done.";