#!/bin/bash
#
# script for moving a container from or to a remote server and
# restoring network settings if set up using the lxc-ip script.
#
# lxc-migrate [remote:]<container> [remote:]<container> [options]
#
# Autor: Henryk Iwaniuk

c1=""  # full name of container to be moved
c_ip=""  # ip to be reapplied to moved container
c2=""  # full name of destination container

get_ip_of_container () {
	c_ip=$(lxc list $1 --format="csv" | awk -F "\"*,\"*" '{print $3}' | cut -f1 -d" ");
}

c_start () {
	lxc start $1;
}

c_stop () {
	lxc stop $1;
}

c_move () {
	lxc move $1 $2;
}

process_input () {
	c1=$1;
	c2=$2;
	echo "get ip"
	get_ip_of_container $c1;
	echo "unset ip"
	lxc-ip unset $c1;
	echo "stop c"
	c_stop $c1;
	echo "move"
	c_move $c1 $c2;

	if [ -z "$c_ip" ]
	then
		echo "not creating a network";
	else
		lxc-ip set $c2 $c_ip;
	fi

	if [ "$3" != "-s" ]
	then
		c_start $c2;
	fi

}

process_input $1 $2;

